/* soapClient.c
   Generated by gSOAP 2.8.91 for service.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.91 2024-06-11 21:34:35 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__translateFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__translateFile *ns1__translateFile, char **ns1__translatedContent)
{	if (soap_send___ns1__translateFile(soap, soap_endpoint, soap_action, ns1__translateFile) || soap_recv___ns1__translateFile(soap, ns1__translatedContent))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__translateFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__translateFile *ns1__translateFile)
{	struct __ns1__translateFile soap_tmp___ns1__translateFile;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://example.com/translator/service";
	if (soap_action == NULL)
		soap_action = "http://example.com/translator/translateFile";
	soap_tmp___ns1__translateFile.ns1__translateFile = ns1__translateFile;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__translateFile(soap, &soap_tmp___ns1__translateFile);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__translateFile(soap, &soap_tmp___ns1__translateFile, "-ns1:translateFile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__translateFile(soap, &soap_tmp___ns1__translateFile, "-ns1:translateFile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__translateFile(struct soap *soap, char **ns1__translatedContent)
{
	struct __ns1__translateFileResponse *soap_tmp___ns1__translateFileResponse;
	if (!ns1__translatedContent)
		return soap_closesock(soap);
	*ns1__translatedContent = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp___ns1__translateFileResponse = soap_get___ns1__translateFileResponse(soap, NULL, "-ns1:translateFileResponse", NULL);
	if (!soap_tmp___ns1__translateFileResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ns1__translatedContent && soap_tmp___ns1__translateFileResponse->ns1__translatedContent)
		*ns1__translatedContent = *soap_tmp___ns1__translateFileResponse->ns1__translatedContent;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
